### PR TITLE
fix: set winminwidth/height before winwidth/height

### LINKED ISSUE #138: Error opening `plenary.nvim` popups: E592: 'winwidth' cannot be smaller than 'winminwidth'
**Steps to reproduce:**

1. Open nvim `nvim -u vimrc` (minimal `vimrc` below)
2. Trigger a `plenary.nvim` popup with `<leader>fg` (`<leader>` is configured to be `<space>`)
3. Observe the error from below.

I figured out that 

```lua
autoresize = {
  minwidth = 80,
},
```

is the source of the error, once the `minwidth` is removed, no error is thrown.

**Minimal Vimrc:**

(using `vundle` for package management)

```vimrc
set nocompatible " be iMproved, required
filetype off     " required

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

set background=dark

" Vundle Stuff
if has("win32") || has("win16")
    call plug#begin('$HOME/vimfiles/bundle/')
else
    call plug#begin('~/.vim/bundle')
endif

" Set mapleader before plugin loads
nnoremap <SPACE> <Nop>
let mapleader=" "
let maplocalleader=" "

if has('nvim')
    " Libraries
    Plug 'kyazdani42/nvim-web-devicons'
    Plug 'nvim-lua/plenary.nvim'               " Lua library

    Plug 'nvim-focus/focus.nvim'

    " Telescope
    Plug 'nvim-telescope/telescope.nvim', { 'branch': '0.1.x' } " Improved LSP actions
    Plug 'nvim-telescope/telescope-live-grep-args.nvim'
    Plug 'nvim-telescope/telescope-ui-select.nvim' " Use telescope as native vim select popup, required from NVIM v0.7.0
    Plug 'nvim-telescope/telescope-fzy-native.nvim'
endif

call plug#end()

" =============================================================================
" Telescope
" =============================================================================
lua << EOF
local actions = require 'telescope.actions'
local lga_actions = require("telescope-live-grep-args.actions")
require('telescope').setup {}
require('telescope').load_extension('live_grep_args')
EOF

nnoremap <leader>fg <cmd>lua require('telescope').extensions.live_grep_args.live_grep_args()<cr>


" =============================================================================
" focus.nvim
" =============================================================================
lua <<EOF
require("focus").setup({
    enable = true, -- Enable module
    autoresize = {
      minwidth = 80, -- this is the culprit, once the `minwidth` is removed, no error is thrown.
    },
})
EOF
```

**NeoVim Version:**

```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Full Error:**

```
E5108: Error executing lua ...tarv/.vim/bundle/plenary.nvim/lua/plenary/popup/init.lua:408: WinEnter Autocommands for "*": Vim(append):Error executin
g lua callback: ...arv/.vim/bundle/focus.nvim/lua/focus/modules/resizer.lua:82: E592: 'winwidth' cannot be smaller than 'winminwidth'
stack traceback:
        [C]: in function '__newindex'
        ...arv/.vim/bundle/focus.nvim/lua/focus/modules/resizer.lua:82: in function 'split_resizer'
        .../home/gerstarv/.vim/bundle/focus.nvim/lua/focus/init.lua:97: in function 'resize'
        ...arv/.vim/bundle/focus.nvim/lua/focus/modules/autocmd.lua:43: in function <...arv/.vim/bundle/focus.nvim/lua/focus/modules/autocmd.lua:37>
        [C]: in function 'nvim_set_current_win'
        ...tarv/.vim/bundle/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
        ...arv/.vim/bundle/telescope.nvim/lua/telescope/pickers.lua:331: in function '_create_window'
        ...arv/.vim/bundle/telescope.nvim/lua/telescope/pickers.lua:401: in function 'find'
        ...p-args.nvim/lua/telescope/_extensions/live_grep_args.lua:79: in function 'live_grep_args'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...tarv/.vim/bundle/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
        ...arv/.vim/bundle/telescope.nvim/lua/telescope/pickers.lua:331: in function '_create_window'
        ...arv/.vim/bundle/telescope.nvim/lua/telescope/pickers.lua:401: in function 'find'
        ...p-args.nvim/lua/telescope/_extensions/live_grep_args.lua:79: in function 'live_grep_args'
        [string ":lua"]:1: in main chunk
```

### PR DESCRIPTION
**Pull request by willothy**
fixes #138 (I think)

### CODE REVIEW

**Comment by rustysec** [comment]
using this branch, it fixes my issue with #138

File: lua/focus/modules/resizer.lua [hunk 1]
```diff
@@ -113,10 +113,10 @@ function M.split_resizer(config, goal) --> Only resize normal buffers, set qf to
         or vim.api.nvim_win_get_config(0).relative ~= ''
         or not config.autoresize.enable
     then
-        vim.o.winwidth = 1
         vim.o.winminwidth = 1
```
Comment (cryptomilk) [inline lua/focus/modules/resizer.lua:116]: Can you add code comments please?

**Review by cryptomilk — CHANGES_REQUESTED** [review]

File: lua/focus/modules/resizer.lua (hunk 1 above)
Comment (willothy) [reply lua/focus/modules/resizer.lua:118]: Done :)
